[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "joy2key_sdl"
version = "4.8"
dependencies = [
  "PySDL2",
]
requires-python = ">=3.8"
description = "Command line joystick to keyboard translator, using SDL2 for event handling"
license = {file = "LICENSE.md"}
classifiers = [
  "Programming Language :: Python"
]


[project.urls]
Repository = "https://github.com/RetroPie/RetroPie-Setup"

[project.scripts]
joy2keyd = "joy2key_sdl:main"

[tool.hatch.build]
include=["joy2key_sdl.py"]
