# Generated by Django 4.2.5 on 2023-10-17 15:42

from django.db import migrations


def apply_migration(apps, schema_editor):
    # Create all permissions
    Light = apps.get_model("backend", "Light")
    Fixture = apps.get_model("backend", "Fixture")

    def create_blinder(name):
        b = Fixture.objects.create(name=name, kind="blinder")
        for i in range(4):
            for j in range(4):
                Light.objects.create(
                    name=f"{name}_{j}_{i}",
                    fixture=b,
                    offset=i + 4 * j,
                )

    def create_led_tub(name):
        b = Fixture.objects.create(name=name, kind="led_tub")
        for i in range(16):
            Light.objects.create(
                name=f"{name}_{i}",
                fixture=b,
                offset=i,
            )

    def create_par_led(name):
        b = Fixture.objects.create(name=name, kind="par_led")
        Light.objects.create(
            name=f"{name}",
            fixture=b,
            offset=0,
        )

    create_blinder("Blinder")
    create_led_tub("Tube LED 1")
    create_led_tub("Tube LED 2")
    create_led_tub("Tube LED 3")
    create_par_led("Par LED scene-gauche")
    create_par_led("Par LED scene-droit")
    create_par_led("Par LED cote-gauche")
    create_par_led("Par LED cote-droit")


def revert_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [migrations.RunPython(apply_migration, revert_migration)]
